"""training/: veri dışa aktarma (bağlam, hatalı tur ayıklama, gizlilik), Modelfile ve devreye alma kararı."""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from training.evaluate import score_goal  # noqa: E402
from training.export_dataset import Scrubber, samples_from_run  # noqa: E402
from training.import_model import build_modelfile  # noqa: E402
from training.promote import decide  # noqa: E402


def _turns():
    return [
        {"turn": 0, "system": "SİSTEM", "user": "TEST HEDEFİ: TESTR ile ticaret", "goal": "ticaret", "model": "gemini",
         "history_turns": 2},
        {"turn": 1, "text": "bakıyorum", "calls": [{"name": "observe", "args": {}}],
         "results": [{"name": "observe", "content": {"nearby": [{"type": "pc", "name": "TESTR", "vid": 5},
                                                                  {"type": "pc", "name": "AI_QA_002", "vid": 6}],
                                                      "messages": [{"text": "TESTR : selam kardeş"},
                                                                   {"text": "[QA] OK reset"}]}}]},
        {"turn": 2, "text": "", "calls": [{"name": "walk_to", "args": {"vid": 5}}],
         "results": [{"name": "walk_to", "content": {"ok": False, "error": "ValueError: walk_to: missing a required argument: 'x'"}}]},
        {"turn": 3, "text": "", "calls": [{"name": "trade_with", "args": {"name": "TESTR"}}],
         "results": [{"name": "trade_with", "content": {"step": 1, "status": "passed"}}], "note": "İlerleme: 1/20"},
        {"turn": 4, "text": "", "calls": [{"name": "finish", "args": {"summary": "TESTR ile ticaret açıldı"}}],
         "results": [{"name": "finish", "content": {"ok": True}}]},
    ]


def test_samples_mirror_inference_context_and_skip_invalid_turns():
    s = samples_from_run({"run_id": "QA-1"}, _turns(), {})
    assert [x["meta"]["turn"] for x in s] == [1, 3, 4]          # hatalı argümanlı tur 2 hedef değil
    last = s[-1]["messages"]
    assert last[0] == {"role": "system", "content": "SİSTEM"}
    assert last[1]["content"] == "TEST HEDEFİ: Oyuncu#1 ile ticaret"
    # history_turns=2: tur 4 için yalnızca tur 2 ve 3 bağlamda (hatalı tur bağlamda kalır)
    roles = [m["role"] for m in last[2:]]
    assert roles == ["assistant", "tool", "assistant", "tool", "user", "assistant"]
    assert last[-1]["tool_calls"][0]["function"] == {"name": "finish", "arguments": {"summary": "Oyuncu#1 ile ticaret açıldı"}} \
        or last[-1]["tool_calls"][0]["function"]["name"] == "finish"
    first_obs = s[0]["messages"][-1]
    assert first_obs["role"] == "assistant"
    ctx = json.dumps(s[1]["messages"], ensure_ascii=False)
    assert "TESTR" not in ctx and "Oyuncu#1" in ctx and "AI_QA_002" in ctx
    assert "selam kardeş" not in ctx and "[QA] OK reset" in ctx     # başkasının sohbeti atılır


def test_scrubber_keeps_qa_accounts():
    sc = Scrubber()
    sc.learn({"nearby": [{"type": "pc", "name": "Ali"}, {"type": "pc", "name": "AI_QA_003"}]})
    assert sc.text("Ali ve AI_QA_003") == "Oyuncu#1 ve AI_QA_003"


def test_score_goal_counts_argument_errors_as_invalid():
    m = score_goal({"check": {"type": "distinct_args", "tool": "trade_with", "keys": ["name"], "min": 1}},
                   _turns(), {"stop_reason": "finished"})
    assert m["invalid"] == 1 and m["calls"] == 2 and m["goal"] == 1.0 and m["finish"] == 1.0


def test_modelfile_keeps_template_and_swaps_from(tmp_path):
    base = '# Modelfile generated by "ollama show"\nFROM C:\\blobs\\sha256-x\nTEMPLATE """{{ .Tools }}"""\n' \
           'PARAMETER stop <|im_end|>\nLICENSE """uzun lisans"""\n'
    g = tmp_path / "m.gguf"
    g.write_bytes(b"x")
    mf = build_modelfile(base, g)
    assert mf.startswith(f"FROM {g.resolve().as_posix()}")
    assert 'TEMPLATE """{{ .Tools }}"""' in mf and "PARAMETER stop <|im_end|>" in mf
    assert "LICENSE" not in mf and "#" not in mf


def test_promotion_decision():
    cur = {"score": 0.6, "goals": [{"goal_id": "a", "score": 0.6}, {"goal_id": "b", "score": 0.6}]}
    better = {"score": 0.7, "goals": [{"goal_id": "a", "score": 0.8}, {"goal_id": "b", "score": 0.6}]}
    regress = {"score": 0.7, "goals": [{"goal_id": "a", "score": 1.0}, {"goal_id": "b", "score": 0.2}]}
    assert decide(better, cur, 0.02, 0.25)[0]
    assert not decide(regress, cur, 0.02, 0.25)[0]                  # bir hedefte çok gerileme
    assert not decide({"score": 0.61, "goals": []}, cur, 0.02, 0.25)[0]
    assert decide(better, None, 0.02, 0.25)[0]
